name: Alfresco ROOT Web Application CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_release:
    name: "Build and Release"
    uses: Alfresco/alfresco-build-tools/.github/workflows/build-and-release-maven.yml@v2.6.0
    secrets: inherit
    with:
      build-args: "-Dmaven.javadoc.skip=true"